services:
  nginx:
    image: nginx:alpine
    container_name: controle-estoque-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

  web:
    build: .
    container_name: controle-estoque-web
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=senha123
      - DB_NAME=estoque
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    container_name: controle-estoque-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: estoque
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./bd/banco.sql:/docker-entrypoint-initdb.d/banco.sql

volumes:
  db_data:
